Repository CodIN-INU/BACKEND, pull requests merged in 2024-12, with the labels that each got.

#26 [SC-86] Refresh Token 로직 변경
  src/main/java/inu/codin/codin/common/config/SecurityConfig.java
  src/main/java/inu/codin/codin/common/config/SwaggerConfig.java
  src/main/java/inu/codin/codin/common/security/controller/AuthController.java
  src/main/java/inu/codin/codin/common/security/filter/ExceptionHandlerFilter.java
  src/main/java/inu/codin/codin/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/inu/codin/codin/common/security/jwt/JwtUtils.java
  src/main/java/inu/codin/codin/common/security/service/JwtService.java
Labels: ✨ Feature

#28 [SC-90] RateLimit 기능 추가
  build.gradle
  src/main/java/inu/codin/codin/common/config/Bucket4jRateLimitApp.java
  src/main/java/inu/codin/codin/common/ratelimit/ClientIpUtil.java
  src/main/java/inu/codin/codin/common/ratelimit/RateLimitBucketConstants.java
  src/main/java/inu/codin/codin/common/ratelimit/RateLimitInterceptor.java
  src/main/java/inu/codin/codin/common/ratelimit/RateLimitService.java
  src/main/java/inu/codin/codin/common/response/RateLimitResponse.java
Labels: ✨ Feature

#25 [SC-81] ChatRoom & Chatting
  build.gradle
  src/main/java/inu/codin/codin/CodinApplication.java
  src/main/java/inu/codin/codin/common/config/SecurityConfig.java
  src/main/java/inu/codin/codin/common/config/WebSocketConfig.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/dto/ChatRoomCreateRequestDto.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/dto/ChatRoomListResponseDto.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/entity/ChatRoom.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/entity/Participants.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/exception/ChatRoomNotFoundException.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/repository/ChatRoomRepository.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/service/ChatRoomService.java
  src/main/java/inu/codin/codin/domain/chat/chatting/controller/ChattingController.java
  src/main/java/inu/codin/codin/domain/chat/chatting/dto/request/ChattingRequestDto.java
  src/main/java/inu/codin/codin/domain/chat/chatting/dto/response/ChattingResponseDto.java
  src/main/java/inu/codin/codin/domain/chat/chatting/entity/Chatting.java
  src/main/java/inu/codin/codin/domain/chat/chatting/entity/MessageType.java
  src/main/java/inu/codin/codin/domain/chat/chatting/exception/ChattingNotFoundException.java
  src/main/java/inu/codin/codin/domain/chat/chatting/repository/ChattingRepository.java
  src/main/java/inu/codin/codin/domain/chat/chatting/repository/ChattingRepositoryCustomImpl.java
  src/main/java/inu/codin/codin/domain/chat/chatting/repository/CustomChattingRepository.java
  src/main/java/inu/codin/codin/domain/chat/chatting/service/ChattingService.java
Labels: ✨ Feature

#33 fix : Swagger에서 JWT 토큰 적용
  src/main/java/inu/codin/codin/common/config/SecurityConfig.java
  src/main/java/inu/codin/codin/common/config/SwaggerConfig.java
Labels: 🐞 BugFix

#39 [Sc 81] 채팅 기능 추가
  build.gradle
  src/main/java/inu/codin/codin/CodinApplication.java
  src/main/java/inu/codin/codin/common/config/SecurityConfig.java
  src/main/java/inu/codin/codin/common/config/WebSocketConfig.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/controller/ChatRoomController.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/dto/ChatRoomCreateRequestDto.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/dto/ChatRoomListResponseDto.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/entity/ChatRoom.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/entity/Participants.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/exception/ChatRoomNotFoundException.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/repository/ChatRoomRepository.java
  src/main/java/inu/codin/codin/domain/chat/chatroom/service/ChatRoomService.java
  src/main/java/inu/codin/codin/domain/chat/chatting/ChatPreHandler.java
  src/main/java/inu/codin/codin/domain/chat/chatting/controller/ChattingController.java
  src/main/java/inu/codin/codin/domain/chat/chatting/dto/ContentType.java
  src/main/java/inu/codin/codin/domain/chat/chatting/dto/request/ChattingRequestDto.java
  src/main/java/inu/codin/codin/domain/chat/chatting/dto/response/ChattingResponseDto.java
  src/main/java/inu/codin/codin/domain/chat/chatting/entity/Chatting.java
  src/main/java/inu/codin/codin/domain/chat/chatting/entity/MessageType.java
  src/main/java/inu/codin/codin/domain/chat/chatting/exception/ChattingNotFoundException.java
  src/main/java/inu/codin/codin/domain/chat/chatting/repository/ChattingRepository.java
  src/main/java/inu/codin/codin/domain/chat/chatting/repository/CustomChattingRepository.java
  src/main/java/inu/codin/codin/domain/chat/chatting/service/ChattingService.java
  src/main/java/inu/codin/codin/domain/post/service/PostService.java
  src/main/java/inu/codin/codin/infra/s3/S3Service.java
Labels: ✨ Feature

#38 [SC-95] feat : 게시글 Pageable 설정
  src/main/java/inu/codin/codin/domain/post/controller/PostController.java
  src/main/java/inu/codin/codin/domain/post/dto/response/PostPageResponse.java
  src/main/java/inu/codin/codin/domain/post/repository/PostRepository.java
  src/main/java/inu/codin/codin/domain/post/service/PostService.java
Labels: ✨ Feature

#41 Sc 96 user post
  src/main/java/inu/codin/codin/domain/post/controller/PostController.java
  src/main/java/inu/codin/codin/domain/post/domain/comment/repository/CommentRepository.java
  src/main/java/inu/codin/codin/domain/post/domain/like/repository/LikeRepository.java
  src/main/java/inu/codin/codin/domain/post/domain/scrap/repository/ScrapRepository.java
  src/main/java/inu/codin/codin/domain/post/service/PostService.java
  src/main/java/inu/codin/codin/domain/user/controller/UserController.java
  src/main/java/inu/codin/codin/domain/user/service/UserService.java
Labels: ✨ Feature

#43 Refactor/timestamp&password
  src/main/java/inu/codin/codin/common/config/SecurityConfig.java
  src/main/java/inu/codin/codin/common/security/util/SecurityUtils.java
  src/main/java/inu/codin/codin/domain/email/controller/EmailController.java
  src/main/java/inu/codin/codin/domain/email/service/EmailAuthService.java
  src/main/java/inu/codin/codin/domain/email/service/EmailSendService.java
  src/main/java/inu/codin/codin/domain/post/domain/comment/dto/response/CommentResponseDTO.java
  src/main/java/inu/codin/codin/domain/post/domain/comment/service/CommentService.java
  src/main/java/inu/codin/codin/domain/post/domain/reply/service/ReplyCommentService.java
  src/main/java/inu/codin/codin/domain/user/controller/UserController.java
  src/main/java/inu/codin/codin/domain/user/dto/UserDeleteRequestDto.java
  src/main/java/inu/codin/codin/domain/user/dto/UserPasswordRequestDto.java
  src/main/java/inu/codin/codin/domain/user/entity/UserEntity.java
  src/main/java/inu/codin/codin/domain/user/exception/UserPasswordChangeFailException.java
  src/main/java/inu/codin/codin/domain/user/repository/UserRepository.java
  src/main/java/inu/codin/codin/domain/user/service/UserService.java
Labels: ✨ Feature

#45 feat : 유저 정보 반환
  src/main/java/inu/codin/codin/domain/user/controller/UserController.java
  src/main/java/inu/codin/codin/domain/user/dto/request/UserCreateRequestDto.java
  src/main/java/inu/codin/codin/domain/user/dto/request/UserDeleteRequestDto.java
  src/main/java/inu/codin/codin/domain/user/dto/request/UserPasswordRequestDto.java
  src/main/java/inu/codin/codin/domain/user/dto/response/UserInfoResponseDto.java
  src/main/java/inu/codin/codin/domain/user/service/UserService.java
Labels: ✨ Feature

#50 Develop
  src/main/java/inu/codin/codin/domain/email/service/EmailAuthService.java
  src/main/java/inu/codin/codin/domain/post/domain/comment/service/CommentService.java
  src/main/java/inu/codin/codin/domain/post/domain/hits/HitsEntity.java
  src/main/java/inu/codin/codin/domain/post/domain/hits/HitsRepository.java
  src/main/java/inu/codin/codin/domain/post/domain/reply/service/ReplyCommentService.java
  src/main/java/inu/codin/codin/domain/post/dto/response/PostDetailResponseDTO.java
  src/main/java/inu/codin/codin/domain/post/dto/response/PostListResponseDto.java
  src/main/java/inu/codin/codin/domain/post/dto/response/PostPageResponse.java
  src/main/java/inu/codin/codin/domain/post/entity/PostCategory.java
  src/main/java/inu/codin/codin/domain/post/repository/PostRepository.java
  src/main/java/inu/codin/codin/domain/post/service/PostService.java
  src/main/java/inu/codin/codin/infra/redis/RedisService.java
  src/main/java/inu/codin/codin/infra/redis/SyncScheduler.java
Labels: ✨ Feature

#53 refactor : User 이미지 업로드, multipart/form-data 변경
  src/main/java/inu/codin/codin/domain/user/controller/UserController.java
  src/main/java/inu/codin/codin/domain/user/dto/request/UserCreateRequestDto.java
  src/main/java/inu/codin/codin/domain/user/service/UserService.java
Labels: 🔨 Refactor

#54 feat/user-edit 유저 정보 수정 기능 추가
  src/main/java/inu/codin/codin/domain/user/controller/UserController.java
  src/main/java/inu/codin/codin/domain/user/dto/request/UserUpdateRequestDto.java
  src/main/java/inu/codin/codin/domain/user/entity/UserEntity.java
  src/main/java/inu/codin/codin/domain/user/service/UserService.java
Labels: ✨ Feature

#58 SC-102 Top3 Best 게시글 반환
  src/main/java/inu/codin/codin/common/BaseTimeEntity.java
  src/main/java/inu/codin/codin/domain/post/controller/PostController.java
  src/main/java/inu/codin/codin/domain/post/domain/comment/entity/CommentEntity.java
  src/main/java/inu/codin/codin/domain/post/domain/comment/service/CommentService.java
  src/main/java/inu/codin/codin/domain/post/domain/like/repository/LikeRepository.java
  src/main/java/inu/codin/codin/domain/post/domain/like/service/LikeService.java
  src/main/java/inu/codin/codin/domain/post/domain/reply/controller/ReplyCommentController.java
  src/main/java/inu/codin/codin/domain/post/domain/reply/entity/ReplyCommentEntity.java
  src/main/java/inu/codin/codin/domain/post/domain/reply/service/ReplyCommentService.java
  src/main/java/inu/codin/codin/domain/post/domain/scrap/controller/ScrapController.java
  src/main/java/inu/codin/codin/domain/post/domain/scrap/repository/ScrapRepository.java
  src/main/java/inu/codin/codin/domain/post/domain/scrap/service/ScrapService.java
  src/main/java/inu/codin/codin/domain/post/service/PostService.java
  src/main/java/inu/codin/codin/domain/user/service/UserService.java
  src/main/java/inu/codin/codin/infra/redis/RedisService.java
  src/main/java/inu/codin/codin/infra/redis/SyncScheduler.java
Labels: ✨ Feature

#69 feat : 댓글, 대댓글에서의 유저 좋아요 여부 반환
  src/main/java/inu/codin/codin/domain/post/domain/comment/dto/response/CommentResponseDTO.java
  src/main/java/inu/codin/codin/domain/post/domain/comment/service/CommentService.java
  src/main/java/inu/codin/codin/domain/post/domain/reply/dto/request/ReplyCreateRequestDTO.java
  src/main/java/inu/codin/codin/domain/post/domain/reply/service/ReplyCommentService.java
  src/main/java/inu/codin/codin/infra/redis/RedisService.java
  src/main/java/inu/codin/codin/infra/redis/SyncScheduler.java
Labels: 🔨 Refactor
