Repository CodIN-INU/BACKEND, pull requests merged in 2024-11, with the labels that each got.

#1 기본 Spring Boot Setting 적용
  .idea/.gitignore
  .idea/vcs.xml
  HELP.md
  build.gradle
  gradlew
  gradlew.bat
  settings.gradle
Labels: ⚙ Setting, Status: Done

#3 기본 DB 세팅 #2
  .gitignore
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  src/main/java/inu/codin/codin/CodinApplication.java
  src/main/java/inu/codin/codin/infra/redis/RedisConfig.java
  src/main/java/inu/codin/codin/infra/redis/RedisProperties.java
  src/main/java/inu/codin/codin/infra/s3/S3Config.java
  src/test/java/inu/codin/codin/CodinApplicationTests.java
  src/test/java/inu/codin/codin/infra/redis/RedisConfigTest.java
Labels: ⚙ Setting

#4 이슈 템플릿 추가 및 gitignore 수정
  .github/ISSUE_TEMPLATE/3-setting.yml
  .gitignore
Labels: ⚙ Setting

#6 Scrum 50 swagger setting
  build.gradle
  src/main/java/inu/codin/codin/TestController.java
  src/main/java/inu/codin/codin/common/config/SwaggerConfig.java
Labels: ⚙ Setting, ✨ Feature

#7 [SC-58] 이메일인증 모듈 추가
  build.gradle
  src/main/java/inu/codin/codin/common/config/MailConfig.java
  src/main/java/inu/codin/codin/common/exception/EmailAuthFailException.java
  src/main/java/inu/codin/codin/domain/email/controller/EmailController.java
  src/main/java/inu/codin/codin/domain/email/dto/JoinEmailCheckRequestDto.java
  src/main/java/inu/codin/codin/domain/email/dto/JoinEmailSendRequestDto.java
  src/main/java/inu/codin/codin/domain/email/entity/EmailAuthEntity.java
  src/main/java/inu/codin/codin/domain/email/repository/EmailAuthRepository.java
  src/main/java/inu/codin/codin/domain/email/service/EmailAuthService.java
  src/main/java/inu/codin/codin/domain/email/service/EmailSendService.java
Labels: ✨ Feature, Status: Reviewing

#8 [SC-56] 회원가입기능추가
  src/main/java/inu/codin/codin/common/config/SecurityConfig.java
  src/main/java/inu/codin/codin/domain/email/controller/EmailController.java
  src/main/java/inu/codin/codin/domain/email/dto/JoinEmailSendRequestDto.java
  src/main/java/inu/codin/codin/domain/email/entity/EmailAuthEntity.java
  src/main/java/inu/codin/codin/domain/email/exception/EmailAuthFailException.java
  src/main/java/inu/codin/codin/domain/email/service/EmailAuthService.java
  src/main/java/inu/codin/codin/domain/user/controller/UserController.java
  src/main/java/inu/codin/codin/domain/user/dto/UserCreateRequestDto.java
  src/main/java/inu/codin/codin/domain/user/entity/Department.java
  src/main/java/inu/codin/codin/domain/user/entity/UserEntity.java
  src/main/java/inu/codin/codin/domain/user/entity/UserRole.java
  src/main/java/inu/codin/codin/domain/user/entity/UserStatus.java
  src/main/java/inu/codin/codin/domain/user/exception/UserCreateFailException.java
  src/main/java/inu/codin/codin/domain/user/repository/UserRepository.java
  src/main/java/inu/codin/codin/domain/user/service/UserService.java
Labels: ✨ Feature

#9 Sc 66 post entity dto
  build.gradle
  src/main/java/inu/codin/codin/CodinApplication.java
  src/main/java/inu/codin/codin/common/BaseTimeEntity.java
  src/main/java/inu/codin/codin/common/config/MailConfig.java
  src/main/java/inu/codin/codin/common/config/SecurityConfig.java
  src/main/java/inu/codin/codin/domain/email/controller/EmailController.java
  src/main/java/inu/codin/codin/domain/email/dto/JoinEmailCheckRequestDto.java
  src/main/java/inu/codin/codin/domain/email/dto/JoinEmailSendRequestDto.java
  src/main/java/inu/codin/codin/domain/email/entity/EmailAuthEntity.java
  src/main/java/inu/codin/codin/domain/email/exception/EmailAuthFailException.java
  src/main/java/inu/codin/codin/domain/email/repository/EmailAuthRepository.java
  src/main/java/inu/codin/codin/domain/email/service/EmailAuthService.java
  src/main/java/inu/codin/codin/domain/email/service/EmailSendService.java
  src/main/java/inu/codin/codin/domain/post/dto/request/PostAnonymousUpdateReqDTO.java
  src/main/java/inu/codin/codin/domain/post/dto/request/PostContentUpdateReqDTO.java
  src/main/java/inu/codin/codin/domain/post/dto/request/PostCreateReqDTO.java
  src/main/java/inu/codin/codin/domain/post/dto/request/PostStatusUpdateReqDTO.java
  src/main/java/inu/codin/codin/domain/post/dto/response/PostDetailResDTO.java
  src/main/java/inu/codin/codin/domain/post/entity/PostCategory.java
  src/main/java/inu/codin/codin/domain/post/entity/PostEntity.java
  src/main/java/inu/codin/codin/domain/post/entity/PostStatus.java
  src/main/java/inu/codin/codin/domain/user/controller/UserController.java
  src/main/java/inu/codin/codin/domain/user/dto/UserCreateRequestDto.java
  src/main/java/inu/codin/codin/domain/user/entity/Department.java
  src/main/java/inu/codin/codin/domain/user/entity/UserEntity.java
  src/main/java/inu/codin/codin/domain/user/entity/UserRole.java
  src/main/java/inu/codin/codin/domain/user/entity/UserStatus.java
  src/main/java/inu/codin/codin/domain/user/exception/UserCreateFailException.java
  src/main/java/inu/codin/codin/domain/user/repository/UserRepository.java
  src/main/java/inu/codin/codin/domain/user/service/UserService.java
Labels: ✨ Feature

#12 [SC-57] 로그인기능추가
  build.gradle
  src/main/java/inu/codin/codin/CodinApplication.java
  src/main/java/inu/codin/codin/TestController.java
  src/main/java/inu/codin/codin/common/config/SecurityConfig.java
  src/main/java/inu/codin/codin/common/config/SwaggerConfig.java
  src/main/java/inu/codin/codin/common/security/controller/AuthController.java
  src/main/java/inu/codin/codin/common/security/dto/LoginRequestDto.java
  src/main/java/inu/codin/codin/common/security/exception/JwtException.java
  src/main/java/inu/codin/codin/common/security/exception/SecurityErrorCode.java
  src/main/java/inu/codin/codin/common/security/filter/ExceptionHandlerFilter.java
  src/main/java/inu/codin/codin/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/inu/codin/codin/common/security/jwt/JwtAuthenticationToken.java
  src/main/java/inu/codin/codin/common/security/jwt/JwtTokenProvider.java
  src/main/java/inu/codin/codin/common/security/jwt/JwtUtils.java
  src/main/java/inu/codin/codin/common/security/service/JwtService.java
  src/main/java/inu/codin/codin/common/security/service/RedisStorageService.java
  src/main/java/inu/codin/codin/domain/user/controller/UserController.java
  src/main/java/inu/codin/codin/domain/user/exception/UserDisabledException.java
  src/main/java/inu/codin/codin/domain/user/repository/UserRepository.java
  src/main/java/inu/codin/codin/domain/user/security/CustomUserDetails.java
  src/main/java/inu/codin/codin/domain/user/security/CustomUserDetailsService.java
  src/main/java/inu/codin/codin/domain/user/service/UserService.java
  src/main/java/inu/codin/codin/infra/redis/RedisConfig.java
  src/main/java/inu/codin/codin/infra/redis/RedisProperties.java
Labels: ✨ Feature

#13 SCRUM-55-로그인시스템기능추가
  build.gradle
  src/main/java/inu/codin/codin/CodinApplication.java
  src/main/java/inu/codin/codin/TestController.java
  src/main/java/inu/codin/codin/common/BaseTimeEntity.java
  src/main/java/inu/codin/codin/common/config/MailConfig.java
  src/main/java/inu/codin/codin/common/config/SecurityConfig.java
  src/main/java/inu/codin/codin/common/config/SwaggerConfig.java
  src/main/java/inu/codin/codin/common/security/controller/AuthController.java
  src/main/java/inu/codin/codin/common/security/dto/LoginRequestDto.java
  src/main/java/inu/codin/codin/common/security/exception/JwtException.java
  src/main/java/inu/codin/codin/common/security/exception/SecurityErrorCode.java
  src/main/java/inu/codin/codin/common/security/filter/ExceptionHandlerFilter.java
  src/main/java/inu/codin/codin/common/security/filter/JwtAuthenticationFilter.java
  src/main/java/inu/codin/codin/common/security/jwt/JwtAuthenticationToken.java
  src/main/java/inu/codin/codin/common/security/jwt/JwtTokenProvider.java
  src/main/java/inu/codin/codin/common/security/jwt/JwtUtils.java
  src/main/java/inu/codin/codin/common/security/service/JwtService.java
  src/main/java/inu/codin/codin/common/security/service/RedisStorageService.java
  src/main/java/inu/codin/codin/domain/email/controller/EmailController.java
  src/main/java/inu/codin/codin/domain/email/dto/JoinEmailCheckRequestDto.java
  src/main/java/inu/codin/codin/domain/email/dto/JoinEmailSendRequestDto.java
  src/main/java/inu/codin/codin/domain/email/entity/EmailAuthEntity.java
  src/main/java/inu/codin/codin/domain/email/exception/EmailAuthFailException.java
  src/main/java/inu/codin/codin/domain/email/repository/EmailAuthRepository.java
  src/main/java/inu/codin/codin/domain/email/service/EmailAuthService.java
  src/main/java/inu/codin/codin/domain/email/service/EmailSendService.java
  src/main/java/inu/codin/codin/domain/user/controller/UserController.java
  src/main/java/inu/codin/codin/domain/user/dto/UserCreateRequestDto.java
  src/main/java/inu/codin/codin/domain/user/entity/Department.java
  src/main/java/inu/codin/codin/domain/user/entity/UserEntity.java
  src/main/java/inu/codin/codin/domain/user/entity/UserRole.java
  src/main/java/inu/codin/codin/domain/user/entity/UserStatus.java
  src/main/java/inu/codin/codin/domain/user/exception/UserCreateFailException.java
  src/main/java/inu/codin/codin/domain/user/exception/UserDisabledException.java
  src/main/java/inu/codin/codin/domain/user/repository/UserRepository.java
  src/main/java/inu/codin/codin/domain/user/security/CustomUserDetails.java
  src/main/java/inu/codin/codin/domain/user/security/CustomUserDetailsService.java
  src/main/java/inu/codin/codin/domain/user/service/UserService.java
  src/main/java/inu/codin/codin/infra/redis/RedisConfig.java
  src/main/java/inu/codin/codin/infra/redis/RedisProperties.java
Labels: ✨ Feature, Priority : High

#14 Sc 71 정보대소개
  src/main/java/inu/codin/codin/common/Department.java
  src/main/java/inu/codin/codin/domain/info/lab/controller/LabController.java
  src/main/java/inu/codin/codin/domain/info/lab/dto/LabListResDTO.java
  src/main/java/inu/codin/codin/domain/info/lab/dto/LabThumbnailResDTO.java
  src/main/java/inu/codin/codin/domain/info/lab/entity/Lab.java
  src/main/java/inu/codin/codin/domain/info/lab/exception/LabNotFoundException.java
  src/main/java/inu/codin/codin/domain/info/lab/repository/LabRepository.java
  src/main/java/inu/codin/codin/domain/info/lab/service/LabService.java
  src/main/java/inu/codin/codin/domain/info/office/controller/OfficeController.java
  src/main/java/inu/codin/codin/domain/info/office/dto/OfficeListResDTO.java
  src/main/java/inu/codin/codin/domain/info/office/dto/OfficeMember.java
  src/main/java/inu/codin/codin/domain/info/office/dto/OfficeMemberResDTO.java
  src/main/java/inu/codin/codin/domain/info/office/entity/Office.java
  src/main/java/inu/codin/codin/domain/info/office/repository/OfficeRepository.java
  src/main/java/inu/codin/codin/domain/info/office/service/OfficeService.java
  src/main/java/inu/codin/codin/domain/info/professor/controller/ProfessorController.java
  src/main/java/inu/codin/codin/domain/info/professor/dto/ProfessorListResDTO.java
  src/main/java/inu/codin/codin/domain/info/professor/dto/ProfessorThumbnailResDTO.java
  src/main/java/inu/codin/codin/domain/info/professor/entity/Professor.java
  src/main/java/inu/codin/codin/domain/info/professor/exception/ProfessorNotFoundException.java
  src/main/java/inu/codin/codin/domain/info/professor/repository/ProfessorRepository.java
  src/main/java/inu/codin/codin/domain/info/professor/service/ProfessorService.java
  src/main/java/inu/codin/codin/domain/user/dto/UserCreateRequestDto.java
  src/main/java/inu/codin/codin/domain/user/entity/UserEntity.java
  src/main/java/inu/codin/codin/domain/user/security/CustomUserDetails.java
Labels: ✨ Feature

#15 [SC-67] Feat : 게시물 생성시 content(JSON) +다중 ImageFile 업로드
  src/main/java/inu/codin/codin/common/config/WebConfig.java
  src/main/java/inu/codin/codin/common/util/MultipartJackson2HttpMessageConverter.java
  src/main/java/inu/codin/codin/domain/post/controller/PostController.java
  src/main/java/inu/codin/codin/domain/post/dto/request/PostAnonymousUpdateRequestDTO.java
  src/main/java/inu/codin/codin/domain/post/dto/request/PostContentUpdateRequestDTO.java
  src/main/java/inu/codin/codin/domain/post/dto/request/PostCreateReqDTO.java
  src/main/java/inu/codin/codin/domain/post/dto/request/PostStatusUpdateRequestDTO.java
  src/main/java/inu/codin/codin/domain/post/dto/response/PostDetailResponseDTO.java
  src/main/java/inu/codin/codin/domain/post/entity/PostEntity.java
  src/main/java/inu/codin/codin/domain/post/service/PostService.java
  src/main/java/inu/codin/codin/infra/s3/S3Service.java
Labels: ✨ Feature, Status: Reviewing

#19 @Valid 추가
  src/main/java/inu/codin/codin/domain/info/domain/lab/controller/LabController.java
  src/main/java/inu/codin/codin/domain/info/domain/office/controller/OfficeController.java
  src/main/java/inu/codin/codin/domain/info/domain/professor/controller/ProfessorController.java
Labels: 🔨 Refactor

#23 Refactor/combine response
  src/main/java/inu/codin/codin/common/GlobalExceptionHandler.java
  src/main/java/inu/codin/codin/common/response/CommonResponse.java
  src/main/java/inu/codin/codin/common/response/ExceptionResponse.java
  src/main/java/inu/codin/codin/common/response/ListResponse.java
  src/main/java/inu/codin/codin/common/response/SingleResponse.java
  src/main/java/inu/codin/codin/domain/email/controller/EmailController.java
  src/main/java/inu/codin/codin/domain/info/domain/lab/controller/LabController.java
  src/main/java/inu/codin/codin/domain/info/domain/office/controller/OfficeController.java
  src/main/java/inu/codin/codin/domain/info/domain/professor/controller/ProfessorController.java
  src/main/java/inu/codin/codin/domain/user/controller/UserController.java
Labels: ✨ Feature, 🔨 Refactor
